#!/usr/bin/python

import argparse
import getpass
from tzlocal import get_localzone


import pytz
import time

from src.dude import keep, tell, list_absolute_keys

if __name__ == '__main__':
    username = getpass.getuser()

    parser = argparse.ArgumentParser(prog="shell_dude", description='A dude in need is a dude indeed!')
    parser.add_argument('-k', '--keep', required=False, dest='tags', nargs='?',
                        help="Tag your secret to retrieve it later")
    parser.add_argument('-l', '--list', dest='lst', required=False, action='store_true',
                        help="List all tags")
    parser.add_argument('secret', help="Tell your secret or ask for one")
    args = parser.parse_args()

    if args.tags:
        keys, secret_id = keep(args.secret, args.tags, username)
        print(
            "Secret kept! You may retrieve it using following keys: %s\nInternal ID: %s" % (", ".join(keys), secret_id))
    elif args.lst:
        keys = list_absolute_keys(username)
        print("\n".join(keys))
    else:
        secrets = tell(args.secret, username)
        for (id, key, secret, ts) in secrets:
            ts = ts.replace(tzinfo=pytz.UTC).astimezone(get_localzone()).strftime("%c")
            print("[%s] %s - %s" % (ts, key, secret))
