#!/usr/bin/python

import argparse
import getpass

from src.dude import keep, tell, list_absolute_keys
from src.exceptions import ConstraintFailure

if __name__ == '__main__':
    username = getpass.getuser()

    parser = argparse.ArgumentParser(prog="shell_dude", description='A dude in need is a dude indeed!')
    parser.add_argument('-k', '--keep', required=False, dest='tags', nargs='?',
                        help="Tag your secret to retrieve it later")
    parser.add_argument('-l', '--list', dest='lst', required=False, action='store_true',
                        help="List all tags")
    parser.add_argument('secret', help="Tell your secret or ask for one")
    args = parser.parse_args()

    if args.tags:
        try:
            keys, secret_id = keep(args.secret, args.tags, username)
            print("Secret kept! You may retrieve it using following keys: %s" % ", ".join(keys))
        except ConstraintFailure as cfe:
            print("Youch! %s" % cfe)
    elif args.lst:
        try:
            keys = list_absolute_keys(username)
            print("\n".join(keys))
        except ConstraintFailure as cfe:
            print("Youch! %s" % cfe)

    else:
        secrets = tell(args.secret, username)
        for (id, key, secret, score) in secrets:
            print("%.2f  %s" % (score, secret))
